name: Comment

on:
  pull_request:

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"
      - name: Run test coverage
        run: |
          go test ./... -coverprofile cover.out
          echo "go test" >> result
          echo '```' >> result
          go tool cover -func cover.out >> result
          echo '```' >> result
      - name: Comment
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr comment ${{ github.event.pull_request.number }} -F ./result --repo ${{ github.repository }}
  coverage-using-covdata:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"
      - name: Run test coverage
        run: |
          go build -cover cmd/main.go 
          mkdir cov
          GOCOVERDIR=cov ./main
          echo "covdata" >> result
          echo '```' >> result
          go tool covdata func -i cov >> result
          echo '```' >> result
      - name: Comment
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr comment ${{ github.event.pull_request.number }} -F ./result --repo ${{ github.repository }}
      - name: Summary
        run: |
          cat ./result >> $GITHUB_STEP_SUMMARY
