name: Comment

on:
  pull_request:

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"
      - name: Run test coverage
        run: |
          go test ./... -coverprofile cover.out
      - uses: actions/github-script@v6
        with:
          github-token: ${{ github.token }}
          script: |
            const output = `\`\`\`go test cover\n
            ${ go tool cover -func cover.out}
            \`\`\`
            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
  coverage-using-covdata:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"
      - name: Run test coverage
        run: |
          go build -cover cmd/main.go 
          mkdir cov
          GOCOVERDIR=cov ./main
          go tool covdata func -i cov > result
      - name: Comment
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr comment ${{ github.event.pull_request.number }} -F ./result --repo ${{ github.repository }}